version: "3.9"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/mamasync-backend:latest
    container_name: mamasync-backend
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/mamasync-frontend:latest
    container_name: mamasync-frontend
    ports:
      - "80:80"
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: mamasync-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: mamasync-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: always
