version: "3.9"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/mamasync-backend-render:render
    container_name: mamasync-backend-render
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/mamasync-frontend-render:render
    container_name: mamasync-frontend-render
    ports:
      - "80:80"
    restart: always

